name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to tag

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Hatch
        run: pip install hatch

      - name: Get version from __init__.py
        id: version
        run: |
          VERSION=$(hatch version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Tag release
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag "v${{ steps.version.outputs.version }}"
          git push origin "v${{ steps.version.outputs.version }}"

      - name: Build package
        run: hatch build

      - name: Publish to PyPI
        env:
          HATCH_INDEX_AUTH: "pypi=${{ secrets.PYPI_API_TOKEN }}"
        run: hatch publish
